### PR TITLE
PHPDoc for autocomplete while coding a migration

### PR DESCRIPTION
**Pull request by thallisphp**

### CODE REVIEW

**Comment by abderrahmane-tj** [comment]
Why isn't this pull request merged already ?

**Comment by Mike724** [comment]
I'd like to also see this merged and in a future release

**Comment by GrahamCampbell** [comment]
Wong repository. Please CLOSE this.

**Comment by Mike724** [comment]
I have recreated this pull request in the correct repo: https://github.com/laravel/framework/pull/8506

**Comment by GrahamCampbell** [comment]
> Please CLOSE this.

**Pull request closed without merging**
