### PR TITLE
new feature collection

### PR DESCRIPTION
**Pull request by agoalofalife**
Sometimes i want to execute something if the collection is not empty
I think it would be convenient to pass callback

`collect(['one', 'two'])->isNotEmptyAction(function($collections) {
        $collections->last();
});`

### CODE REVIEW

**Comment by SergeyPodgornyy** [comment]
PSR-2 standard conflicts - http://www.php-fig.org/psr/psr-2/
- Opening braces for control structures MUST go on the same line, and closing braces MUST go on the next line after the body.
- Opening parentheses for control structures MUST NOT have a space after them, and closing parentheses for control structures MUST NOT have a space before.

**Comment by SergeyPodgornyy** [comment]
Useless feature, you can just use:

```php
$last = collect(['one', 'two'])->last();
```

It will automatically check if it's not empty

**Comment by agoalofalife** [comment]
@SergeyPodgornyy this is just an example, not necessarily method `last` should be called
it can be anything, for example we can perform an action when the lack of data in the database

**Comment by SergeyPodgornyy** [comment]
@agoalofalife Then you can do something like this:

```php
function customFunction()
{
    echo 'Collection is empty';
}

collect(['one', 'two'])->isNotEmpty() && customFunction();
```

If collection will be empty, your function will be executed

**Comment by agoalofalife** [comment]
the question is not how to solve the problem, and how to simplify
for example, a method `isNotEmpty` can also be replaced to 
```
if empty($collect->all()) ...
or 

$collect->count() > 0
```
and the like..
the essence is that we provide explicit tools for working with the collection
I do not call, for all other cases is Macroable trait

**Comment by SergeyPodgornyy** [comment]
You are not simplifying logic, while adding useless functionality. If you need to call some function or do some action if collection is not empty, you can do this easier by writing the following:
```php
collect(['one', 'two'])->isNotEmpty() && customFunction();
```
And then, there is no need in function you wrote :slightly_smiling_face: 

@taylorotwell Please let us know your opinion

**Pull request closed without merging**
